// 列表
export const ORDERS_LIST_REQUEST = 'ORDERS.LIST_REQUEST';
export const ORDERS_LIST_SUCCESS = 'ORDERS.LIST_SUCCESS';
export const ORDERS_LIST_FAIL    = 'ORDERS.LIST_FAIL';

// 取消
export const ORDERS_CANCEL_REQUEST = 'ORDERS.CANCEL_REQUEST';
export const ORDERS_CANCEL_SUCCESS = 'ORDERS.CANCEL_SUCCESS';
export const ORDERS_CANCEL_FAIL    = 'ORDERS.CANCEL_FAIL';
