export const ADD_PRODUCT_REQUEST  = 'ADD_PRODUCT_REQUEST';
export const ADD_PRODUCT_SUCCESS  = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAIL     = 'ADD_PRODUCT_FAIL';

export const LIST_PRODUCTS_REQUEST = 'LIST_PRODUCTS_REQUEST';
export const LIST_PRODUCTS_SUCCESS = 'LIST_PRODUCTS_SUCCESS';
export const LIST_PRODUCTS_FAIL    = 'LIST_PRODUCTS_FAIL';
