export const HOSPITAL_LIST_REQUEST = "HOSPITAL_LIST_REQUEST";
export const HOSPITAL_LIST_SUCCESS = "HOSPITAL_LIST_SUCCESS";
export const HOSPITAL_LIST_FAIL    = "HOSPITAL_LIST_FAIL";
export const HOSPITAL_LIST_CLEAR   = "HOSPITAL_LIST_CLEAR";

export const HOSPITAL_VACCINES_REQUEST = "HOSPITAL_VACCINES_REQUEST";
export const HOSPITAL_VACCINES_SUCCESS = "HOSPITAL_VACCINES_SUCCESS";
export const HOSPITAL_VACCINES_FAIL    = "HOSPITAL_VACCINES_FAIL";
