export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL    = "USER_LIST_FAIL";

export const USER_SET_CURRENT  = "USER_SET_CURRENT";
export const USER_CLEAR_CURRENT= "USER_CLEAR_CURRENT";
